-- 0015 — payment terms on draft invoices generated by recurring schedules. When set, issuing the
-- draft sets the due date to at least issue date + due_days, so a catch-up draft issued late is not
-- overdue the day it is sent. Editing the draft's due date by hand clears it.

ALTER TABLE invoice
    ADD COLUMN due_days INTEGER CHECK (due_days IS NULL OR due_days BETWEEN 0 AND 3650);
